var atxt1="Email Address is incorrect (check @ y's.)",
atxt2="The user name is invalid.",
atxt3="invalid IP destination",
atxt4="The domain appears to be invalid",
atxt5="Management should have 3 letters if .'com 'or 2 if in any country of",
atxt6="The address is wrong",
atxt7="You must enter a valid email address",
atxt8="You must enter the password",
atxt9="You must enter the card number",
atxt10="You must input the names",
atxt11="You must input the surnames",
atxt12="You must enter the email",
atxt13="You must enter the password",
atxt14="You must confirm the password",atxt15="both keys must match",atxt16="You must enter the date of birth",atxt17="You must enter the subject",atxt18="You must enter the Message",atxt19="You must enter the Phone Number",atxt20="You must select the amount of product",atxt21="You must enter the shipping address",atxt22="You must enter the destination city",atxt23="You must enter the destination state",atxt24="You must enter the country of destination",atxt25="You must enter the telephone contact",atxt26="Invalid Username or Password",atxt27="Failed to register try again later!",atxt28="Card number already registered Check your data!",atxt29="Email already registered Please check your data!",atxt30="Failed to register try again later!",atxt31="Your update was successful. Now you can log in with the new password!",atxt32="It was not possible to update attempt later!",atxt33="Your message was processed successfully!",atxt34="It was not possible sending the message, try again later!",atxt35="You must enter a valid card number!",atxt36="Product Added to Cart!",atxt37="You must select the rating",atxt38="You must enter your review",atxt39="Thanks for comment on this product!",atxt40="Great!!!",atxt41="You must enter The Product Code",atxt42="Product Deleted";